# File automatically-generated by STM32CubeMX - Do not modify
cmake_minimum_required(VERSION 3.22)
# STM32CubeMX generated symbols (macros)
set(MX_Defines_Syms 
	CORE_CM7 
	USE_HAL_DRIVER 
	STM32H755xx 
	USE_PWR_DIRECT_SMPS_SUPPLY
    $<$<CONFIG:Debug>:DEBUG>
)
# STM32CubeMX generated include paths
set(MX_Include_Dirs
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/LWIP/App
    ${CMAKE_CURRENT_SOURCE_DIR}/LWIP/Target
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/system
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Inc
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/include
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/CMSIS/RTOS2/Include
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/BSP/Components/lan8742
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/netif/ppp
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/BSP/STM32H7xx_Nucleo
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/CMSIS/Device/ST/STM32H7xx/Include
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/lwip
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/lwip/apps
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/lwip/priv
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/lwip/prot
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/netif
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/compat/posix
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/compat/posix/net
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/include/compat/stdc
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/system/arch
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/CMSIS/Include
)
# STM32CubeMX generated application sources
set(MX_Application_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/main.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/freertos.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/stm32h7xx_it.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/stm32h7xx_hal_msp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/stm32h7xx_hal_timebase_tim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/sysmem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/syscalls.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LWIP/Target/ethernetif.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LWIP/App/lwip.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Startup/startup_stm32h755xx_CM7.s
)

# STM32 HAL/LL Drivers
set(STM32_Drivers_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Common/Src/system_stm32h7xx_dualcore_boot_cm4_cm7.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/BSP/Components/lan8742/lan8742.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/BSP/STM32H7xx_Nucleo/stm32h7xx_nucleo.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Drivers/BSP/Components/lan8742/lan8742.c
)

# Drivers Midllewares

set(FreeRTOS_Src
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/portable/Common/mpu_wrappers_v2.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/croutine.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/list.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/queue.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/tasks.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/timers.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c
)
set(LwIP_Src
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/auth.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/ccp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/chap_ms.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/chap-md5.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/chap-new.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/demand.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/eap.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/eui64.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/fsm.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/ipcp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/ipv6cp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/lcp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/magic.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/mppe.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/multilink.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/ppp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/pppapi.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/pppcrypt.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/pppoe.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/pppol2tp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/pppos.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/upap.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/utils.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/vj.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/bridgeif.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/bridgeif_fdb.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ethernet.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/lowpan6.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/lowpan6_ble.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/lowpan6_common.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/slipif.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/zepif.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/netif/ppp/ecp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/netbuf.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/api_msg.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/netdb.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/tcpip.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/if_api.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/err.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/sockets.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/netifapi.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/api/api_lib.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/def.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/dns.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/stats.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/altcp_tcp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/pbuf.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/tcp_out.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/udp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ip.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/netif.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/tcp_in.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/altcp_alloc.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/altcp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/raw.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/inet_chksum.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/tcp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/timeouts.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/init.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/mem.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/memp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/sys.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/acd.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/nd6.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/dhcp6.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/mld6.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_frag.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/icmp6.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_addr.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/ethip6.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/core/ipv6/inet6.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/system/OS/sys_arch.c
    /home/aleks/STM32Cube/Repository/STM32Cube_FW_H7_V1.13.0/Middlewares/Third_Party/LwIP/src/apps/mqtt/mqtt.c
)

# Link directories setup
set(MX_LINK_DIRS

)
# Project libraries
set (MX_LINK_LIBS 
    STM32_Drivers
    ${TOOLCHAIN_LINK_LIBRARIES}
    FreeRTOS	LwIP	
    
)
# Interface library for includes and symbols
add_library(stm32cubemx INTERFACE)
target_include_directories(stm32cubemx INTERFACE ${MX_Include_Dirs})
target_compile_definitions(stm32cubemx INTERFACE ${MX_Defines_Syms})

# Create STM32_Drivers static library
add_library(STM32_Drivers OBJECT)
target_sources(STM32_Drivers PRIVATE ${STM32_Drivers_Src})
target_link_libraries(STM32_Drivers PUBLIC stm32cubemx)

# Create FreeRTOS static library
add_library(FreeRTOS OBJECT)
target_sources(FreeRTOS PRIVATE ${FreeRTOS_Src})
target_link_libraries(FreeRTOS PUBLIC stm32cubemx)

# Create LwIP static library
add_library(LwIP OBJECT)
target_sources(LwIP PRIVATE ${LwIP_Src})
target_link_libraries(LwIP PUBLIC stm32cubemx)


# Add STM32CubeMX generated application sources to the project
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${MX_Application_Src})

# Link directories setup
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE ${MX_LINK_DIRS})

# Add libraries to the project
target_link_libraries(${CMAKE_PROJECT_NAME} ${MX_LINK_LIBS})

# Add the map file to the list of files to be removed with 'clean' target
set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES ADDITIONAL_CLEAN_FILES ${CMAKE_PROJECT_NAME}.map)




# Validate that STM32CubeMX code is compatible with C standard
if((CMAKE_C_STANDARD EQUAL 90) OR (CMAKE_C_STANDARD EQUAL 99))
    message(ERROR "Generated code requires C11 or higher")
endif()