#!/usr/bin/env python3
"""pair_v2: option-4 pairing with freshness from both sides.

pair_v1 bound nothing fresh into the key derivation. Z is a function of the two
static keys and hub_eph alone, so a recorded PAIR_RSP re-derives the same
session key forever and replaying it re-installs an old key with every check
passing. Found by the device side. The fix is that both ends now contribute:
the request's superframe (monotone, durable through the flash ceiling) and an
8-byte device nonce (unpredictable, and independent of the join beacon, which
is cleartext by necessity and therefore forgeable).

Written from the specification in words rather than from either firmware, so a
diff against the device side's independent generator tests the specification.

Self-checks the curve, the KDF and pair_v1's Z terms before emitting anything.
"""
import hashlib
import hmac
import os
import re
import struct
import sys

sys.path.insert(0, "tools/pairing")
import p256

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

# --- inputs, pinned so the two generators can be diffed at all ---------------
HUB_EPH_PRIVATE = 0x4b3a291807f6e5d4c3b2a1907e6d5c4b3a2918070605040302010f0e0d0c0b0a
DEV_NONCE       = bytes.fromhex("a1b2c3d4e5f60718")
REQ_SUPERFRAME  = 0x1a2b3c4d   # no zero byte: a byte-order slip cannot land plausibly
NET_ID          = 0x0001
VERSION         = 2

# PAIR_ACCEPT goes out later in the exchange than the request it answers.
ACCEPT_SUPERFRAME = 0x1a2b3c4f
ACCEPT_RETRY      = 0
GRANT_SLOT         = 0
GRANT_REPORT_EVERY = 8
GRANT_FLAGS        = 0
# Random per hub in the field. Fixed here so the frame bytes are reproducible.
NET_HOP_KEY = bytes(range(16))

UPLINK_SUPERFRAME = 0x1a2b3c58
UPLINK_SLOT       = 0
RPT_RSSI_DOWN = -92
RPT_FLAGS     = 0
RPT_SUPPLY_MV = 3287
RPT_UPTIME_S  = 61

DIR_UPLINK   = 0x01
DIR_DOWNLINK = 0x02
NONCE_SLOT_UNSLOTTED = 0xFFFF00


# The digest covers the pinned values, in a canonical form, and nothing else.
# radio_devices_docs/open_hub/arch/build-and-generation.md
def value_digest(rows):
    body = "".join(f"{k}={v}\n" for k, v in sorted(rows))
    return hashlib.sha256(body.encode()).hexdigest()[:16]


def hkdf_sha256(secret: bytes, salt: bytes, info: bytes, length: int) -> bytes:
    prk = hmac.new(salt, secret, hashlib.sha256).digest()
    okm, t, i = b"", b"", 1
    while len(okm) < length:
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        okm += t
        i += 1
    return okm[:length]


def load(path):
    v = {}
    for line in open(path):
        m = re.match(r"\s*(\w+)\s*=\s*([0-9a-fA-F]+)\s*$", line)
        if m:
            v[m.group(1)] = m.group(2)
    return v


def nonce(superframe: int, dev_id: int, direction: int, slot: int) -> bytes:
    """The 12-byte GCM nonce. Big-endian throughout, unlike the frame fields."""
    return (struct.pack(">I", superframe) + struct.pack(">I", dev_id)
            + bytes([direction]) + struct.pack(">I", slot)[1:])


def selfcheck(v):
    for who in ("hub", "dev"):
        d = int(v[f"{who}_private"], 16)
        if p256.compress(p256.mul(d, p256.G)).hex() != v[f"{who}_public_compressed"]:
            sys.exit(f"curve does not reproduce {who}_public")
    dev_pub = p256.decompress(bytes.fromhex(v["dev_public_compressed"]))
    if p256.ecdh_x(int(v["hub_private"], 16), dev_pub).hex() != v["ecdh_shared_x_only"]:
        sys.exit("curve does not reproduce ecdh_shared_x_only")
    salt_v1 = bytes.fromhex(v["hkdf_salt_hubid_devid_be"])
    if hkdf_sha256(bytes.fromhex(v["ecdh_shared_x_only"]), salt_v1,
                   b"openhub/v1/session", 16).hex() != v["key_session_gen0"]:
        sys.exit("HKDF does not reproduce key_session_gen0")

    # The same AES-GCM wire_v3 pinned, so this is not its first use here.
    ct = AESGCM(bytes.fromhex(v["key_session_gen0"])).encrypt(
        bytes.fromhex(v["gcm_nonce"]), bytes.fromhex(v["gcm_plaintext"]),
        bytes.fromhex(v["gcm_aad"]))
    if ct.hex() != v["gcm_ciphertext"] + v["gcm_tag"]:
        sys.exit("AES-GCM does not reproduce wire_v3's sealed frame")
    print("selfcheck curve + hkdf + gcm against wire_v3   ok\n")


def carr(name, data):
    body = ", ".join(f"0x{b:02x}" for b in data)
    wrapped, line = [], "    "
    for tok in body.split(", "):
        if len(line) + len(tok) + 2 > 76:
            wrapped.append(line.rstrip())
            line = "    "
        line += tok + ", "
    wrapped.append(line.rstrip().rstrip(","))
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + "\n".join(wrapped) + "\n};\n"


# The same bytes as C, emitted rather than transcribed.
# radio_devices_docs/open_hub/arch/build-and-generation.md
def emit_header(rows, digest):
    d = dict(rows)
    h = ["/* Generated by tools/pairing/gen_pair_v2_vectors.py - do not edit. */",
         "/* Immutable once published: both firmwares compile against this. */",
         "#pragma once", "", "#include <stdint.h>", "",
         "#define PAIR_VECTORS_VERSION 2",
         f'#define PAIR_VECTORS_DIGEST  "{digest}"',
         f'#define PAIR_REQ_SUPERFRAME  0x{d["pair_req_superframe"]}u',
         ""]
    for name, key in [
            ("PV_DEV_NONCE", "pair_dev_nonce"),
            ("PV_HUB_EPH_PUB", "pair_hub_eph_public_compressed"),
            ("PV_FINGERPRINT", "pair_fingerprint"),
            ("PV_Z", "pair_z"),
            ("PV_SALT", "pair_salt"),
            ("PV_KEY_SESSION", "pair_key_session"),
            ("PV_KEY_ROOT", "pair_key_root"),
            ("PV_CONFIRM_KEY_HUB", "pair_confirm_key_hub"),
            ("PV_CONFIRM_KEY_DEV", "pair_confirm_key_dev"),
            ("PV_TRANSCRIPT", "pair_transcript"),
            ("PV_CONFIRM_HUB", "pair_confirm_hub"),
            ("PV_CONFIRM_DEV", "pair_confirm_dev"),
            ("PV_NET_HOP_KEY", "pair_net_hop_key"),
            ("PV_ACCEPT_NONCE", "pair_accept_nonce"),
            ("PV_ACCEPT_AAD", "pair_accept_aad"),
            ("PV_ACCEPT_PLAIN", "pair_accept_plaintext"),
            ("PV_FRAME_REQ", "frame_pair_req"),
            ("PV_FRAME_RSP", "frame_pair_rsp"),
            ("PV_FRAME_CONF", "frame_pair_conf"),
            ("PV_FRAME_ACCEPT", "frame_pair_accept"),
            ("PV_UPLINK_NONCE", "uplink_nonce"),
            ("PV_UPLINK_AAD", "uplink_aad"),
            ("PV_UPLINK_PLAIN", "uplink_plaintext"),
            ("PV_FRAME_UPLINK", "frame_uplink")]:
        h.append(carr(name, bytes.fromhex(d[key])))
    return "\n".join(h)


def main():
    v = load("Common/test/vectors/wire_v3.txt")
    selfcheck(v)

    hub_static_d = int(v["hub_private"], 16)
    dev_static_d = int(v["dev_private"], 16)
    hub_static_c = bytes.fromhex(v["hub_public_compressed"])
    dev_static_c = bytes.fromhex(v["dev_public_compressed"])
    hub_id, dev_id = 0x33442211, 0x0000002A

    hub_eph_pt = p256.mul(HUB_EPH_PRIVATE, p256.G)
    hub_eph_c = p256.compress(hub_eph_pt)

    # Hub term first in every concatenation: Z1 authenticates, Z2 is freshness.
    z1 = p256.ecdh_x(hub_static_d, p256.decompress(dev_static_c))
    z2 = p256.ecdh_x(HUB_EPH_PRIVATE, p256.decompress(dev_static_c))
    assert z1 == p256.ecdh_x(dev_static_d, p256.decompress(hub_static_c))
    assert z2 == p256.ecdh_x(dev_static_d, hub_eph_pt)
    assert z1.hex() == v["ecdh_shared_x_only"], "Z1 is still wire_v3's ECDH"
    z = z1 + z2

    # 20 bytes: the two identities, then both contributions of freshness.
    salt = (struct.pack(">I", hub_id) + struct.pack(">I", dev_id)
            + struct.pack(">I", REQ_SUPERFRAME) + DEV_NONCE)
    assert len(salt) == 20

    k_session = hkdf_sha256(z, salt, b"openhub/v1/session", 16)
    k_root    = hkdf_sha256(z, salt, b"openhub/v1/root", 32)
    k_cf_hub  = hkdf_sha256(z, salt, b"openhub/v1/confirm/hub", 32)
    k_cf_dev  = hkdf_sha256(z, salt, b"openhub/v1/confirm/dev", 32)

    t = (struct.pack(">I", hub_id) + struct.pack(">I", dev_id)
         + struct.pack(">I", REQ_SUPERFRAME) + DEV_NONCE
         + hub_static_c + hub_eph_c + dev_static_c)
    assert len(t) == 119

    c_hub = hmac.new(k_cf_hub, t, hashlib.sha256).digest()[:16]
    c_dev = hmac.new(k_cf_dev, t, hashlib.sha256).digest()[:16]

    fingerprint = hashlib.sha256(dev_static_c).digest()

    # --- the frames, byte for byte -----------------------------------------

    # Struct fields are little-endian and the crypto inputs above big-endian.
    # radio_devices_docs/radio/crypto/wire-crypto.md
    req = (struct.pack("<BBHIII", 0x03, VERSION, NET_ID, hub_id, dev_id,
                       REQ_SUPERFRAME) + DEV_NONCE + dev_static_c)
    assert len(req) == 57
    rsp = struct.pack("<BBII", 0x04, VERSION, hub_id, dev_id) + hub_eph_c + c_hub
    assert len(rsp) == 59
    conf = struct.pack("<BBII", 0x05, VERSION, hub_id, dev_id) + c_dev
    assert len(conf) == 26

    grant = bytes([GRANT_SLOT, GRANT_REPORT_EVERY, GRANT_FLAGS]) + NET_HOP_KEY
    assert len(grant) == 19
    acc_hdr = struct.pack("<BBIIIB", 0x06, VERSION, hub_id, dev_id,
                          ACCEPT_SUPERFRAME, ACCEPT_RETRY)
    assert len(acc_hdr) == 15
    acc_nonce = nonce(ACCEPT_SUPERFRAME, dev_id, DIR_DOWNLINK,
                      NONCE_SLOT_UNSLOTTED | ACCEPT_RETRY)
    sealed = AESGCM(k_session).encrypt(acc_nonce, grant, acc_hdr)
    accept = acc_hdr + sealed
    assert len(accept) == 50

    report = struct.pack("<bBHI", RPT_RSSI_DOWN, RPT_FLAGS, RPT_SUPPLY_MV,
                         RPT_UPTIME_S)
    assert len(report) == 8
    up_hdr = struct.pack("<BBBI", 0x07, VERSION, UPLINK_SLOT, UPLINK_SUPERFRAME)
    assert len(up_hdr) == 7
    up_nonce = nonce(UPLINK_SUPERFRAME, dev_id, DIR_UPLINK, UPLINK_SLOT)
    uplink = up_hdr + AESGCM(k_session).encrypt(up_nonce, report, up_hdr)
    assert len(uplink) == 31

    out = [
        ("pair_dev_nonce", DEV_NONCE.hex()),
        ("pair_req_superframe", "%08x" % REQ_SUPERFRAME),
        ("pair_hub_eph_public_compressed", hub_eph_c.hex()),
        ("pair_fingerprint_domain", "compressed-sec1-33"),
        ("pair_fingerprint", fingerprint.hex()),
        ("pair_z1", z1.hex()),
        ("pair_z2", z2.hex()),
        ("pair_z", z.hex()),
        ("pair_salt_len", str(len(salt))),
        ("pair_salt", salt.hex()),
        ("pair_key_session", k_session.hex()),
        ("pair_key_root", k_root.hex()),
        ("pair_confirm_key_hub", k_cf_hub.hex()),
        ("pair_confirm_key_dev", k_cf_dev.hex()),
        ("pair_transcript_len", str(len(t))),
        ("pair_transcript", t.hex()),
        ("pair_transcript_sha256", hashlib.sha256(t).hexdigest()),
        ("pair_confirm_hub", c_hub.hex()),
        ("pair_confirm_dev", c_dev.hex()),
        ("frame_pair_req", req.hex()),
        ("frame_pair_rsp", rsp.hex()),
        ("frame_pair_conf", conf.hex()),
        ("pair_net_hop_key", NET_HOP_KEY.hex()),
        ("pair_accept_superframe", "%08x" % ACCEPT_SUPERFRAME),
        ("pair_accept_nonce", acc_nonce.hex()),
        ("pair_accept_aad", acc_hdr.hex()),
        ("pair_accept_plaintext", grant.hex()),
        ("frame_pair_accept", accept.hex()),
        ("uplink_superframe", "%08x" % UPLINK_SUPERFRAME),
        ("uplink_nonce", up_nonce.hex()),
        ("uplink_aad", up_hdr.hex()),
        ("uplink_plaintext", report.hex()),
        ("frame_uplink", uplink.hex()),
    ]
    header = """# OpenHub pairing vectors, v2
# Generated by tools/pairing/gen_pair_v2_vectors.py from the spec in words.
# Immutable once published. Cross-verified: two independent implementations,
# written from the specification and not from each other's code, produced every
# value below identically.
#
# SUPERSEDES pair_v1. pair_v1 bound nothing fresh into the key derivation, so a
# recorded PAIR_RSP re-derived the same session key forever and replaying it
# re-installed an old key with every check passing. v2 adds the request's
# superframe and an 8-byte device nonce to both the salt and the transcript.
#
# pair_v1's pair_z1 and pair_z2 are unchanged here, and the generator asserts
# it: the ECDH inputs did not move, only what the KDF is salted with. It also
# asserts pair_key_session DID move - a construction that ignored the new
# freshness would otherwise reproduce pair_v1 exactly and look like a working
# port of the fix.
#
# NOT DERIVED, deliberately: pair_key_hop. The hop key is a network key, not a
# pairwise one - a pairwise hop key gives every device a different permutation
# and at most one of them can hear a hub that has one radio. pair_v1's
# pair_key_hop stays pinned and unused. Emitting a v2 replacement would publish
# a second vector with no consumer, which is the exact shape that let the defect
# live in pair_v1 unnoticed. This paragraph exists because an omission and an
# oversight look identical to the next reader.
#
# Field endianness: the crypto inputs below - salt, transcript, nonce - are
# big-endian. The frame_* bytes are the frames as transmitted, and their struct
# fields are LITTLE-endian, because packed C structs on two little-endian cores
# are the contract and the beacons have decoded that way off the air for weeks.
# Both rules are live inside a single frame, which is why whole frames are
# pinned here rather than left to be assembled from the field list.
"""

    lines = [header]
    for k, val in out:
        lines.append(f"{k:32s} = {val}")
    text = "\n".join(lines) + "\n"
    digest = value_digest(out)

    if "--emit" in sys.argv:
        stem = "Common/test/vectors/pair_v2"
        if os.path.exists(stem + ".txt") and "--force" not in sys.argv:
            if open(stem + ".txt").read() != text:
                sys.exit("refusing to rewrite a published set; emit pair_v3 instead")
        open(stem + ".txt", "w").write(text)
        open(stem + ".h", "w").write(emit_header(out, digest))
        print(f"wrote {stem}.txt and {stem}.h   digest {digest}")
    else:
        print(text)
        print(f"# digest = {digest}   (pass --emit to publish)")

    print()
    # A key ignoring the new freshness would reproduce pair_v1 exactly.
    v1 = load("Common/test/vectors/pair_v1.txt")
    print("# key_session moved from pair_v1 (freshness reached the KDF):",
          "ok" if k_session.hex() != v1["pair_key_session"] else "UNCHANGED - SUSPECT")
    print("# transcript moved from pair_v1:",
          "ok" if t.hex() != v1["pair_transcript"] else "UNCHANGED - SUSPECT")
    print("# Z is unchanged from pair_v1 (only the KDF inputs moved):",
          "ok" if z.hex() == v1["pair_z"] else "MOVED - SUSPECT")
    print("# confirmations differ (reflection):", "ok" if c_hub != c_dev else "BROKEN")
    print("# sealed lengths not multiples of four:",
          "ok" if len(grant) % 4 and len(report) % 4 == 0 else "check")


if __name__ == "__main__":
    main()
