#!/usr/bin/env python3
"""pair_v3: the PAIR_INIT frame, which is the only thing v3 adds to the wire.

v3 changes discovery, not the key exchange. Every derivation after PAIR_INIT is
pair_v2's and is pinned in pair_v2.txt; nothing here re-emits it. What is new is
one frame and one key:

    K_init = HKDF(Z1, salt = hub_id||dev_id BE, "openhub/v3/init")
    mac    = HMAC-SHA256(K_init, the frame's first 16 bytes)[:12]

Z1 = X(hub_static * dev_static) is not new either - pair_v2 already publishes it
as `pair_z1`, and both implementations reproduce it. That is the whole reason
this frame is cheap to agree on: its key is a value we already match on.

Written from ADR-0021 in words rather than from firmware, so a diff against the
device side's independent generator tests the specification and not one of the
two implementations of it.

The frame is emitted whole. Its header fields are little-endian because that is
the wire convention, while the HKDF salt is big-endian because that is the
crypto convention - both live inside this one frame, which is exactly the seam
that a round trip agrees with itself about and a published frame does not.
"""
import hashlib
import hmac
import os
import re
import sys

sys.path.insert(0, "tools/pairing")
import p256

# --- pinned inputs ----------------------------------------------------------

# Same identities as pair_v2, so pair_z1 is checked rather than recomputed.
# radio_devices_docs/open_hub/arch/build-and-generation.md
NET_ID     = 0x0001
HUB_ID     = 0x33442211
DEV_ID     = 0x0000002A
VERSION    = 3
FRAME_TYPE = 0x09          # RADIO_FRAME_PAIR_INIT

# No zero byte, so a byte-order slip cannot land looking plausible.
INIT_SUPERFRAME = 0x1a2b3c4d

MAC_BYTES    = 12          # 96 bits; ADR-0021
HEADER_BYTES = 16
FRAME_BYTES  = HEADER_BYTES + MAC_BYTES


def hkdf_sha256(secret: bytes, salt: bytes, info: bytes, length: int) -> bytes:
    prk = hmac.new(salt, secret, hashlib.sha256).digest()
    okm, t, i = b"", b"", 1
    while len(okm) < length:
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        okm += t
        i += 1
    return okm[:length]


def load(path):
    v = {}
    for line in open(path):
        m = re.match(r"\s*(\w+)\s*=\s*([0-9a-fA-F]+)\s*$", line)
        if m:
            v[m.group(1)] = m.group(2)
    return v


def value_digest(pairs):
    """Over the values, not the emitted text.

    A digest of the text makes every comment load-bearing: rewording a
    paragraph moves the digest of a set whose values cannot have changed, and
    everyone holding the old constant is told the vectors moved.
    """
    canon = "\n".join(f"{k}={val}" for k, val in sorted(pairs))
    return hashlib.sha256(canon.encode()).hexdigest()[:16]


def build_init(superframe: int) -> bytes:
    """The 16 cleartext bytes, in wire order. Little-endian, like every other
    frame header in radio_protocol.h."""
    return (bytes([FRAME_TYPE, VERSION])
            + NET_ID.to_bytes(2, "little")
            + HUB_ID.to_bytes(4, "little")
            + DEV_ID.to_bytes(4, "little")
            + superframe.to_bytes(4, "little"))


def carr(name, data):
    body = ", ".join(f"0x{b:02x}" for b in data)
    wrapped, line = [], "    "
    for tok in body.split(", "):
        if len(line) + len(tok) + 2 > 76:
            wrapped.append(line.rstrip())
            line = "    "
        line += tok + ", "
    wrapped.append(line.rstrip().rstrip(","))
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + "\n".join(wrapped) + "\n};\n"


# The same bytes as C, emitted rather than transcribed.
# radio_devices_docs/open_hub/arch/build-and-generation.md
def emit_header(rows, digest):
    d = dict(rows)
    h = ["/* Generated by tools/pairing/gen_pair_v3_vectors.py - do not edit. */",
         "/* Immutable once published: both firmwares compile against this. */",
         "#pragma once", "", "#include <stdint.h>", "",
         "#define PAIR_V3_VECTORS_VERSION 3",
         f'#define PAIR_V3_VECTORS_DIGEST  "{digest}"',
         f'#define PAIR_V3_INIT_SUPERFRAME 0x{d["v3_init_superframe"]}u',
         "",
         "/* The MAC covers PV3_INIT_HEADER exactly; PV3_INIT_FRAME is the two",
         " * concatenated, which is what goes on air. PV3_INIT_FRAME_NEXT_SF is",
         " * the same frame one superframe later - without it a test cannot tell",
         " * a MAC that covers the superframe from one that ignores it. */",
         ""]
    for name, key in [
            ("PV3_INIT_Z1", "v3_init_z1"),
            ("PV3_INIT_KEY", "v3_init_key"),
            ("PV3_INIT_HEADER", "v3_init_header"),
            ("PV3_INIT_MAC", "v3_init_mac"),
            ("PV3_INIT_FRAME", "v3_init_frame"),
            ("PV3_INIT_FRAME_NEXT_SF", "v3_init_frame_next_superframe")]:
        h.append(carr(name, bytes.fromhex(d[key])))
    return "\n".join(h)


def main():
    # Identities in wire_v3, Z1 in pair_v2. Nothing here invents a key.
    v = load("Common/test/vectors/wire_v3.txt")
    v.update(load("Common/test/vectors/pair_v2.txt"))

    hub_static_d = int(v["hub_private"], 16)
    dev_static_d = int(v["dev_private"], 16)
    hub_static_c = bytes.fromhex(v["hub_public_compressed"])
    dev_static_c = bytes.fromhex(v["dev_public_compressed"])

    z1 = p256.ecdh_x(hub_static_d, p256.decompress(dev_static_c))

    # Both directions: a one-sided generator agrees with a one-sided error.
    # radio_devices_docs/open_hub/arch/build-and-generation.md
    if z1 != p256.ecdh_x(dev_static_d, p256.decompress(hub_static_c)):
        sys.exit("Z1 disagrees between the two sides")

    # And against the value pair_v2 already publishes.
    if z1.hex() != v["pair_z1"]:
        sys.exit(f"Z1 does not match published pair_z1\n"
                 f"  computed {z1.hex()}\n  published {v['pair_z1']}")

    # hub_id||dev_id and nothing else; the freshness lives in the message.
    # radio_devices_docs/radio/pairing.md
    salt = HUB_ID.to_bytes(4, "big") + DEV_ID.to_bytes(4, "big")
    if salt.hex() != v["hkdf_salt_hubid_devid_be"]:
        sys.exit("salt disagrees with the published hub_id||dev_id salt")
    if salt.hex() == v["pair_salt"]:
        sys.exit("K_init must not reuse pair_v2's session salt")

    k_init = hkdf_sha256(z1, salt, b"openhub/v3/init", 32)

    header = build_init(INIT_SUPERFRAME)
    assert len(header) == HEADER_BYTES, len(header)
    mac = hmac.new(k_init, header, hashlib.sha256).digest()[:MAC_BYTES]
    frame = header + mac
    assert len(frame) == FRAME_BYTES

    # A second frame at a different superframe: one cannot cover the field.
    # radio_devices_docs/open_hub/security/self-tests.md
    header2 = build_init(INIT_SUPERFRAME + 1)
    mac2 = hmac.new(k_init, header2, hashlib.sha256).digest()[:MAC_BYTES]
    if mac2 == mac:
        sys.exit("the MAC does not cover the superframe")

    out = [
        ("v3_init_z1", z1.hex()),
        ("v3_init_key", k_init.hex()),
        ("v3_init_superframe", f"{INIT_SUPERFRAME:08x}"),
        ("v3_init_header", header.hex()),
        ("v3_init_mac", mac.hex()),
        ("v3_init_frame", frame.hex()),
        ("v3_init_frame_next_superframe", (header2 + mac2).hex()),
    ]

    digest = value_digest(out)
    lines = ["# pair_v3 PAIR_INIT. Generated by tools/pairing/gen_pair_v3_vectors.py",
             "# from ADR-0021, and checked against pair_v2.txt's pair_z1.",
             f"# frame is {FRAME_BYTES} bytes: {HEADER_BYTES} cleartext + "
             f"{MAC_BYTES} MAC",
             ""]
    for k, val in out:
        lines.append(f"{k:32s} = {val}")
    lines.append("")
    lines.append(f"{'v3_value_digest':32s} = {digest}")
    text = "\n".join(lines) + "\n"

    # Immutability: the guard compares whole text, not the digest.
    # radio_devices_docs/radio/crypto/wire-crypto.md
    if "--emit" in sys.argv:
        stem = "Common/test/vectors/pair_v3"
        if os.path.exists(stem + ".txt") and "--force" not in sys.argv:
            if open(stem + ".txt").read() != text:
                sys.exit("refusing to rewrite a published set; emit pair_v4 instead")
        open(stem + ".txt", "w").write(text)
        open(stem + ".h", "w").write(emit_header(out, digest))
        print(f"wrote {stem}.txt and {stem}.h   digest {digest}")
    else:
        print(text)
        print(f"# digest = {digest}   (pass --emit to publish)")


if __name__ == "__main__":
    main()
