#!/usr/bin/env python3
"""Generate the uplink and downlink frame vectors for the v4 wire.

The session key is read from the published pairing set rather than re-derived,
so these frames are anchored to bytes both firmwares already agree on and
cannot drift from them.

pair_v2 pinned one uplink frame at the 8-byte body; the downlink was never
pinned at all. Both directions are here, whole frames, so the little-endian
struct fields meeting the big-endian nonce are checked rather than inferred.

A published set is immutable: the device repository includes the generated
header directly. Changing any value below means emitting link_v(N+1).

See radio_devices_docs/radio/crypto/wire-crypto.md.
"""

import argparse
import hashlib
import os
import struct
import sys

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

VERSION      = 4
DEV_ID       = 0x0000002A
DIR_UPLINK   = 0x01
DIR_DOWNLINK = 0x02

FRAME_UPLINK   = 0x07
FRAME_DOWNLINK = 0x08
CMD_SET_RATE   = 1

# Distinct in every field, so a wrong read names itself instead of matching.
UP_SUPERFRAME = 0x1a2b3c58
UP_SLOT       = 66            # not slot 0: the k=3 stride has to survive the nonce
RPT_RSSI_DOWN = -92
RPT_FLAGS     = 0x01
RPT_SUPPLY_MV = 3287
RPT_UPTIME_S  = 61
RPT_ACK_SEQ   = 0x5B
RPT_ACK_CMD   = CMD_SET_RATE
RPT_APP       = bytes.fromhex("a1b2c3d4e5")

DL_SUPERFRAME = 0x1a2b3c59
DL_SLOT       = 1
DL_REPORT_EVERY = 12
DL_ARG        = 0x1234
DL_HUB_TIME_S = 0x00112233
DL_CMD_SEQ    = 0x5B
DL_APP        = bytes.fromhex("112233445566")


def nonce(superframe, dev_id, direction, slot):
    """superframe(4) || dev_id(4) || direction(1) || slot(3), all big-endian."""
    return (struct.pack(">II", superframe, dev_id) + bytes([direction]) +
            slot.to_bytes(3, "big"))


def value_digest(rows):
    """Over the values, sorted by key: a reworded comment must not move it."""
    canon = "".join("%s=%s\n" % (k, v) for k, v in sorted(rows))
    return hashlib.sha256(canon.encode()).hexdigest()[:16]


def load_session_key(path):
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("pair_key_session"):
                return bytes.fromhex(line.split("=", 1)[1].strip())
    raise SystemExit("pair_key_session not found in %s" % path)


def carr(name, data):
    body = ", ".join("0x%02x" % b for b in data)
    return "static const uint8_t %s[%d] = {\n    %s\n};" % (name, len(data), body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="Common/test/vectors")
    ap.add_argument("--pair", default="Common/test/vectors/pair_v2.txt")
    ap.add_argument("--force", action="store_true",
                    help="overwrite a differing set of the same version. Only safe "
                         "if it was never shared - the device build includes it.")
    args = ap.parse_args()

    k_session = load_session_key(args.pair)

    report = (struct.pack("<bBHI", RPT_RSSI_DOWN, RPT_FLAGS, RPT_SUPPLY_MV,
                          RPT_UPTIME_S) +
              bytes([RPT_ACK_SEQ, RPT_ACK_CMD, len(RPT_APP)]) + RPT_APP)
    assert len(report) == 16, len(report)

    up_hdr = struct.pack("<BBBI", FRAME_UPLINK, VERSION, UP_SLOT, UP_SUPERFRAME)
    assert len(up_hdr) == 7
    up_nonce = nonce(UP_SUPERFRAME, DEV_ID, DIR_UPLINK, UP_SLOT)
    uplink = up_hdr + AESGCM(k_session).encrypt(up_nonce, report, up_hdr)
    assert len(uplink) == 39, len(uplink)

    cmd = (struct.pack("<BBHI", CMD_SET_RATE, DL_REPORT_EVERY, DL_ARG,
                       DL_HUB_TIME_S) +
           bytes([DL_CMD_SEQ, len(DL_APP)]) + DL_APP)
    assert len(cmd) == 16, len(cmd)

    dl_hdr = struct.pack("<BBBI", FRAME_DOWNLINK, VERSION, DL_SLOT, DL_SUPERFRAME)
    assert len(dl_hdr) == 7
    dl_nonce = nonce(DL_SUPERFRAME, DEV_ID, DIR_DOWNLINK, DL_SLOT)
    downlink = dl_hdr + AESGCM(k_session).encrypt(dl_nonce, cmd, dl_hdr)
    assert len(downlink) == 39, len(downlink)

    rows = [
        ("link_key_session", k_session.hex()),
        ("link_proto_version", str(VERSION)),
        ("uplink_superframe", "%08x" % UP_SUPERFRAME),
        ("uplink_slot", str(UP_SLOT)),
        ("uplink_nonce", up_nonce.hex()),
        ("uplink_aad", up_hdr.hex()),
        ("uplink_plaintext", report.hex()),
        ("frame_uplink", uplink.hex()),
        ("downlink_superframe", "%08x" % DL_SUPERFRAME),
        ("downlink_slot", str(DL_SLOT)),
        ("downlink_nonce", dl_nonce.hex()),
        ("downlink_aad", dl_hdr.hex()),
        ("downlink_plaintext", cmd.hex()),
        ("frame_downlink", downlink.hex()),
    ]
    digest = value_digest(rows)

    stem = os.path.join(args.out, "link_v%d" % VERSION)
    text = ("# OpenHub link frame vectors, v%d\n"
            "# Generated by tools/gen_link_vectors.py.\n"
            "# The session key is pair_v2's, read rather than re-derived.\n"
            "# Immutable once published: bump the version to change a value.\n"
            "#\n"
            "# The uplink sits in slot 66, not slot 0, so the k=3 stride is inside\n"
            "# the nonce rather than assumed away by a zero.\n"
            "#\n"
            "# value_digest = %s\n\n" % (VERSION, digest) +
            "".join("%-22s = %s\n" % (k, v) for k, v in rows))

    if os.path.exists(stem + ".txt") and not args.force:
        if open(stem + ".txt", encoding="utf-8").read() != text:
            sys.stderr.write("refusing to rewrite %s.txt with different content.\n"
                             % stem)
            return 1
    with open(stem + ".txt", "w", encoding="utf-8") as f:
        f.write(text)

    h = ["/* Generated by tools/gen_link_vectors.py - do not edit. */",
         "#pragma once", "#include <stdint.h>", "",
         "#define LINK_VECTORS_VERSION %d" % VERSION,
         '#define LINK_VECTORS_DIGEST  "%s"' % digest, ""]
    for name, key in [("LV_KEY_SESSION", "link_key_session"),
                      ("LV_UPLINK_NONCE", "uplink_nonce"),
                      ("LV_UPLINK_AAD", "uplink_aad"),
                      ("LV_UPLINK_PLAIN", "uplink_plaintext"),
                      ("LV_FRAME_UPLINK", "frame_uplink"),
                      ("LV_DOWNLINK_NONCE", "downlink_nonce"),
                      ("LV_DOWNLINK_AAD", "downlink_aad"),
                      ("LV_DOWNLINK_PLAIN", "downlink_plaintext"),
                      ("LV_FRAME_DOWNLINK", "frame_downlink")]:
        h.append(carr(name, bytes.fromhex(dict(rows)[key])))
        h.append("")
    with open(stem + ".h", "w", encoding="utf-8") as f:
        f.write("\n".join(h))
    sys.stderr.write("wrote %s.txt and %s.h, digest %s\n" % (stem, stem, digest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
